// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFuMfIB6dLpcfVyieTLo1qePOBrkh5tc4',
    appId: '1:200338386093:web:724bdb05230906959bea24',
    messagingSenderId: '200338386093',
    projectId: 'shonglap-10bd5',
    authDomain: 'shonglap-10bd5.firebaseapp.com',
    storageBucket: 'shonglap-10bd5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTWd-WohqDrz_whDPns5y7eDtqwOfBl5U',
    appId: '1:200338386093:android:8c2ab374c068ebda9bea24',
    messagingSenderId: '200338386093',
    projectId: 'shonglap-10bd5',
    storageBucket: 'shonglap-10bd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0524Bstdykk8iGdrTmbICyr4zHdKxzzg',
    appId: '1:200338386093:ios:7db070f935beaa369bea24',
    messagingSenderId: '200338386093',
    projectId: 'shonglap-10bd5',
    storageBucket: 'shonglap-10bd5.appspot.com',
    iosBundleId: 'com.example.shonglap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0524Bstdykk8iGdrTmbICyr4zHdKxzzg',
    appId: '1:200338386093:ios:470d1b2d19552c409bea24',
    messagingSenderId: '200338386093',
    projectId: 'shonglap-10bd5',
    storageBucket: 'shonglap-10bd5.appspot.com',
    iosBundleId: 'com.example.shonglap.RunnerTests',
  );
}
